'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const names=['Sprig','Mochi','Nimbus','Bloop','Twinkle','Pip','Pebble','Dusk'],traits=['A curious little leaf with very big ambitions.','A bold fox. Absolutely no thoughts. Only tokens.','Soft clouds, surprisingly competitive.','A bouncy optimist who always lands smiling.','A starry-eyed troublemaker.','Tiny wings. Enormous main-character energy.','Slow vibes. Fast feet.','A midnight dreamer with a mischievous streak.'],colors=['#a7edb8','#ffbb82','#c9b2fa','#91dcf7','#f6a6d0','#ffe798','#81d9c5','#b6a1ef'];
const atlas=new Image();atlas.src='pets.png';let selected=0,running=false,paused=false,ended=false,time=0,last=0,cam=1000,shake=0,charge=0,combo=0,comboTime=0,mapIndex=0,round=0,storm=0,noticeTime=0;
const W=4600,GROUND=720,keys={},pressed={},maps=[{name:'✿ Clover Canopy',sky:['#184c50','#81bda0'],land:'#436e52',top:'#b1ed91',g:1550,speed:1},{name:'☾ Moon Mochi',sky:['#181e48','#6262a2'],land:'#66619b',top:'#c2c1ff',g:760,speed:1},{name:'ϟ Sunset Speedway',sky:['#633a64','#e6ad91'],land:'#915579',top:'#ffc790',g:1550,speed:1.28}];
let pets=[],platforms=[],tokens=[],particles=[],powers=[],rings=[];let audio=null,muted=false,musicClock=0,note=0;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function sound(f=600,len=.07,type='sine',vol=.06){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.65,audio.currentTime+len);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+len)}
function music(dt){if(!audio||muted)return;musicClock-=dt;if(musicClock<=0){musicClock=.22;const melody=[523,659,784,659,880,784,659,587,523,659,1047,880,784,659,587,392];sound(melody[note%16],.17,'sine',.022);if(note%4===0)sound([131,165,175,147][Math.floor(note/4)%4],.3,'triangle',.03);note++}}
function announce(s){$('#notice').textContent=s;noticeTime=3.4}
function burst(x,y,c,n=15){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-180,180),vy:rand(-240,80),life:rand(.3,.8),c,r:rand(2,5)});if(particles.length>350)particles.splice(0,particles.length-350)}
function addToken(x,y,value=1,loose=false){tokens.push({x,y,value,vx:loose?rand(-210,210):0,vy:loose?rand(-380,-150):0,loose,age:0,lock:loose?.45:0})}
function makeMap(){const m=maps[mapIndex];platforms=[{x:0,y:GROUND,w:W,h:100,base:0}];for(let i=0;i<22;i++){const x=100+i*202;const y=GROUND-105-(i%4)*92+Math.sin(i*2+round)*23;platforms.push({x,y,w:rand(135,200),h:25,base:x,moving:i%5===3,phase:rand(0,6),spring:i%6===1});}for(let i=0;i<8;i++)platforms.push({x:220+i*540,y:245+Math.sin(i+round)*72,w:150,h:23,base:220+i*540,moving:i%2===0,phase:i,spring:false});tokens=[];for(let p of platforms.slice(1))for(let j=0;j<4;j++)addToken(p.x+25+j*32,p.y-32,p.y<280?3:1);for(let i=0;i<60;i++)addToken(40+i*75,GROUND-28);powers=[{x:900,y:330,type:'magnet'},{x:2420,y:240,type:'shield'},{x:3650,y:340,type:'speed'}];for(const p of pets){p.x=clamp(p.x,80,W-80);p.y=Math.min(p.y,460);p.vy=0;p.inv=2;p.target=null;}$('#mapName').textContent=m.name;announce(round?'NEW ARENA · '+m.name.toUpperCase():'COLLECT TOKENS · GROW BIG · STOMP RIVALS')}
function pet(id,x){return{id,x,y:500,vx:0,vy:0,score:0,size:1,face:1,ground:false,coyote:0,inv:1,dash:0,cool:0,ai:0,target:null,power:'',powerTime:0,stuck:0,lastX:x}}
function start(){pets=[pet(selected,W/2),...names.map((_,i)=>i).filter(i=>i!==selected).map((id,i)=>pet(id,300+i*610))];time=0;round=0;mapIndex=0;charge=0;combo=0;ended=false;paused=false;running=true;cam=W/2;makeMap();$('#menu').hidden=true;$('#paused').hidden=true;$('#playerName').textContent=names[selected];$('#portrait').style.backgroundPosition=`${selected%4*100/3}% ${Math.floor(selected/4)*100}%`;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}sound(800,.2)}
function spill(v,attacker){if(v.inv>0||v.power==='shield')return;const loss=Math.min(v.score,Math.max(3,Math.ceil(v.score*.23)));v.score-=loss;for(let i=0;i<loss;i++)addToken(v.x,v.y-25,1,true);v.inv=1.5;v.vx=(v.x>=attacker.x?1:-1)*(440+attacker.size*90);v.vy=-440;v.ground=false;burst(v.x,v.y-25,colors[v.id],25);rings.push({x:v.x,y:v.y-25,r:10,life:.35});shake=9;sound(170,.17,'sawtooth');if(attacker===pets[0]){charge=clamp(charge+12,0,100);announce(loss?'TOKEN SPILL! GRAB THE LOOT':'BONK!')} }
function jump(p){if(p.ground||p.coyote>0){p.vy=-650;p.ground=false;p.coyote=0;if(p===pets[0])sound(430,.09);return true}return false}
function ai(p,dt){p.ai-=dt;if(p.ai<=0){p.ai=rand(.3,.65);const choices=tokens.filter(t=>Math.abs(t.x-p.x)<700&&t.y>p.y-320);p.target=choices.sort((a,b)=>(Math.abs(a.x-p.x)+Math.abs(a.y-p.y)*1.3)-(Math.abs(b.x-p.x)+Math.abs(b.y-p.y)*1.3))[0]||{x:rand(100,W-100),y:650};if(Math.abs(p.x-pets[0].x)<220&&Math.random()<.22)p.target={x:clamp(p.x+(p.size>pets[0].size?1:-1)*(pets[0].x-p.x)*2,50,W-50),y:p.y};}
 let target=p.target||{x:p.x,y:600};let dx=target.x-p.x;const above=target.y<p.y-50;if(above){const steps=platforms.slice(1).filter(q=>q.y<p.y-10&&q.y>p.y-155&&Math.abs(q.x+q.w/2-p.x)<320);if(steps.length){steps.sort((a,b)=>Math.abs(a.x+a.w/2-target.x)-Math.abs(b.x+b.w/2-target.x));dx=steps[0].x+steps[0].w/2-p.x;}}
 if(p.ground&&(above||p.stuck>.8||Math.random()<dt*.25))jump(p);if(p.stuck>1.3){dx=p.face*-150;p.stuck=0;p.ai=0;}return Math.abs(dx)>16?Math.sign(dx):0;}
function update(dt){if(!running||paused)return;time+=dt;music(dt);if(time>=180){ended=true;paused=true;const place=[...pets].sort((a,b)=>b.score-a.score).indexOf(pets[0])+1;$('#pauseTitle').textContent=place===1?'Top of the pack!':'What a scramble!';$('#pauseText').textContent=`You placed #${place} with ${pets[0].score} tokens. Ready for a rematch?`;$('#resume').textContent='Play again ➜';$('#paused').hidden=false;return;}
 if(Math.floor(time/30)>round){round=Math.floor(time/30);mapIndex=round%3;makeMap();}const m=maps[mapIndex];$('#timer').textContent=Math.ceil(30-time%30);noticeTime-=dt;if(noticeTime<0)$('#notice').textContent=`${Math.ceil(180-time)}s LEFT · ${storm>0?'TOKEN STORM!':'HIGH ROUTES = BIG REWARDS'}`;
 if(Math.floor(time/20)>Math.floor((time-dt)/20)){storm=4;announce('TOKEN STORM · LOOK UP!');for(let i=0;i<38;i++)addToken(clamp(pets[0].x+rand(-700,700),30,W-30),rand(-100,180),1,true)}storm-=dt;
 for(const q of platforms){q.prev=q.x;if(q.moving)q.x=q.base+Math.sin(time*.8+q.phase)*95;}
 for(let idx=0;idx<pets.length;idx++){const p=pets[idx];p.size=1+Math.min(p.score/75,2);p.inv-=dt;p.cool-=dt;p.dash-=dt;p.powerTime-=dt;if(p.powerTime<=0)p.power='';const r=19*p.size;let dir=idx?ai(p,dt):((keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0));if(dir)p.face=dir;if(!idx){if(pressed.Space||pressed.ArrowUp||pressed.KeyW)jump(p);if(pressed.KeyJ&&p.cool<=0){p.dash=.18;p.cool=1;p.vx=p.face*850;sound(240,.12,'triangle');burst(p.x,p.y-20,'#fff0ad',8)}if(pressed.KeyK&&charge>=100){charge=0;for(const rival of pets.slice(1))if(Math.abs(rival.x-p.x)<370)spill(rival,p);rings.push({x:p.x,y:p.y-30,r:20,life:.7});burst(p.x,p.y-30,'#ffe797',60);sound(1000,.4);shake=14;announce('STAR BURST!')}}
 const speed=285*m.speed*(p.power==='speed'?1.5:1);if(p.dash>0)p.vx=p.face*850;else if(p.inv<1.1)p.vx+=(dir*speed-p.vx)*Math.min(1,dt*(p.ground?16:7));p.vy+=m.g*dt;const oldY=p.y;p.x=clamp(p.x+p.vx*dt,r,W-r);p.y+=p.vy*dt;p.coyote=p.ground?.1:p.coyote-dt;p.ground=false;
 for(const q of platforms)if(p.vy>=0&&oldY<=q.y+4&&p.y>=q.y&&p.x+r*.65>q.x&&p.x-r*.65<q.x+q.w){p.y=q.y;p.vy=0;p.ground=true;if(q.moving)p.x+=q.x-q.prev;if(q.spring){p.vy=-950;p.ground=false;burst(p.x,p.y,'#d4ff98',8);if(!idx)sound(760,.13)}break;}
 if(p.y>900){p.y=500;p.vy=0;p.inv=2;}if(p.y>=GROUND-2&&((p.x>1510&&p.x<1590)||(p.x>3220&&p.x<3300))){spill(p,{x:p.x-1,size:1});p.vy=-600;p.ground=false;if(!idx)announce('HOT PAWS! JUMP OVER THE GLOWING PATCHES');}p.stuck=Math.abs(p.x-p.lastX)<1?p.stuck+dt:0;p.lastX=p.x;
 for(let t=tokens.length-1;t>=0;t--){const tok=tokens[t];if(tok.lock>0)continue;let d=Math.hypot(tok.x-p.x,tok.y-(p.y-r));if(p.power==='magnet'&&d<180){tok.x+=(p.x-tok.x)*dt*7;tok.y+=(p.y-r-tok.y)*dt*7;}if(d<r+15){p.score+=tok.value;tokens.splice(t,1);burst(tok.x,tok.y,'#ffe799',5);if(!idx){combo=comboTime>0?combo+1:1;comboTime=1.6;charge=clamp(charge+tok.value*2,0,100);sound(620+Math.min(combo,15)*38,.06);if(combo%10===0)announce(`${combo} TOKEN COMBO!`);}}}
 for(let j=powers.length-1;j>=0;j--)if(Math.hypot(p.x-powers[j].x,p.y-r-powers[j].y)<r+23){p.power=powers[j].type;p.powerTime=9;powers.splice(j,1);if(!idx){announce(p.power.toUpperCase()+' · 9 SECONDS');sound(1200,.25)}}
 }
 for(let a=0;a<pets.length;a++)for(let b=a+1;b<pets.length;b++){const p=pets[a],q=pets[b],rr=(p.size+q.size)*18;if(Math.abs(p.x-q.x)<rr&&Math.abs((p.y-20*p.size)-(q.y-20*q.size))<rr){if(p.vy>100&&p.y<q.y-10){spill(q,p);p.vy=-520;}else if(q.vy>100&&q.y<p.y-10){spill(p,q);q.vy=-520;}else if(p.dash>0)spill(q,p);else if(q.dash>0)spill(p,q);else if(p.size>q.size*1.2)spill(q,p);else if(q.size>p.size*1.2)spill(p,q);}}
 for(const t of tokens){t.age+=dt;t.lock-=dt;if(t.loose){t.vy+=m.g*dt;t.x=clamp(t.x+t.vx*dt,10,W-10);t.y+=t.vy*dt;if(t.y>GROUND-12){t.y=GROUND-12;t.vy*=-.35;t.vx*=.7;} }}tokens=tokens.filter(t=>!t.loose||t.age<18);if(tokens.length<85&&Math.random()<dt*9){const q=platforms[1+Math.floor(Math.random()*(platforms.length-1))];addToken(q.x+rand(15,q.w-15),q.y-30)}
 comboTime-=dt;for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt}particles=particles.filter(p=>p.life>0);for(const r of rings){r.life-=dt;r.r+=600*dt}rings=rings.filter(r=>r.life>0);cam+=(pets[0].x+pets[0].vx*.24-cam)*Math.min(1,dt*4);shake=Math.max(0,shake-dt*35);$('#score').textContent=pets[0].score;$('#growth').textContent=pets[0].size.toFixed(1)+'× SIZE';$('#charge').style.width=charge+'%';$('#chargeText').textContent=charge>=100?'K · READY!':pets[0].power?pets[0].power.toUpperCase():'Collect to charge';
 $('#ranks').innerHTML=[...pets].sort((a,b)=>b.score-a.score).slice(0,5).map((p,i)=>`<div class="rank ${p===pets[0]?'you':''}"><span>${i+1}</span><i class="dot" style="background:${colors[p.id]}"></i>${names[p.id]}${p===pets[0]?' · you':''}<b>${p.score}</b></div>`).join('');for(const k in pressed)delete pressed[k];}
function rounded(x,y,w,h,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function draw(){const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(innerWidth*dpr)||canvas.height!==Math.round(innerHeight*dpr)){canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);const sw=innerWidth,sh=innerHeight,m=maps[mapIndex],scale=clamp(sh/850,.6,1.2),vw=sw/scale,left=clamp(cam-vw/2,0,Math.max(0,W-vw));let grad=ctx.createLinearGradient(0,0,0,sh);grad.addColorStop(0,m.sky[0]);grad.addColorStop(1,m.sky[1]);ctx.fillStyle=grad;ctx.fillRect(0,0,sw,sh);
 ctx.save();ctx.scale(scale,scale);const vh=sh/scale;for(let i=0;i<35;i++){const x=((i*173-left*.17)%(vw+300)+vw+300)%(vw+300)-100,y=70+(i*97)%490;ctx.globalAlpha=.22;ctx.fillStyle=mapIndex===1?'#e5ddff':'#c6f3c4';ctx.beginPath();ctx.arc(x,y,mapIndex===1?2:randSeed(i)*6+2,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
 for(let layer=0;layer<3;layer++){ctx.fillStyle=[m.sky[0]+'45',m.land+'50',m.land+'70'][layer];ctx.beginPath();ctx.moveTo(0,vh);for(let x=0;x<=vw+40;x+=30){ctx.lineTo(x,500+layer*65+Math.sin((x+left*(.12+layer*.1))/240+layer)*85+Math.cos((x+left*.2)/110)*22)}ctx.lineTo(vw,vh);ctx.fill();}
 ctx.translate(-left+(shake?rand(-shake,shake):0),vh-830+clamp(230-(pets[0]?.y||500),0,450)+(shake?rand(-shake,shake):0));
 for(const p of platforms){if(p.x+p.w<left-100||p.x>left+vw+100)continue;rounded(p.x,p.y,p.w,p.h+20,12,m.land);rounded(p.x,p.y,p.w,9,7,m.top);ctx.fillStyle='#ffffff13';for(let j=12;j<p.w;j+=31){ctx.beginPath();ctx.arc(p.x+j,p.y+23,3,0,7);ctx.fill()}if(p.moving){ctx.strokeStyle=m.top+'50';ctx.setLineDash([5,8]);ctx.beginPath();ctx.moveTo(p.base-95,p.y+45);ctx.lineTo(p.base+p.w+95,p.y+45);ctx.stroke();ctx.setLineDash([])}if(p.spring){rounded(p.x+p.w/2-22,p.y-13,44,13,6,'#ffe993');ctx.fillStyle='#254e49';ctx.font='bold 19px Arial';ctx.textAlign='center';ctx.fillText('↑',p.x+p.w/2,p.y-1)}}
 for(const x of [1510,3220]){rounded(x,GROUND-5,80,12,5,'#ff947f');ctx.fillStyle='#ffe5aa';ctx.font='bold 18px Arial';ctx.textAlign='center';ctx.fillText('≈ ≈ ≈',x+40,GROUND-10);}
 for(const t of tokens){if(t.x<left-30||t.x>left+vw+30)continue;const y=t.y+(t.loose?0:Math.sin(time*3+t.x)*4);ctx.save();ctx.translate(t.x,y);ctx.rotate(Math.PI/4);ctx.shadowColor='#ffd874';ctx.shadowBlur=13;rounded(-7,-7,14,14,3,t.value>1?'#e3c0ff':'#ffe295');ctx.shadowBlur=0;rounded(-3,-3,6,6,1,'#fff9d8');ctx.restore()}
 for(const p of powers){ctx.save();ctx.translate(p.x,p.y+Math.sin(time*3)*6);ctx.rotate(Math.PI/4);rounded(-17,-17,34,34,8,'#bcf9ef');ctx.rotate(-Math.PI/4);ctx.fillStyle='#245c58';ctx.font='bold 21px Arial';ctx.textAlign='center';ctx.fillText(p.type==='magnet'?'U':p.type==='shield'?'◇':'ϟ',0,7);ctx.restore()}
 const order=[...pets].sort((a,b)=>a.size-b.size);for(const p of order){if(p.x<left-120||p.x>left+vw+120)continue;const s=p.size,anim=p.ground?Math.sin(time*(Math.abs(p.vx)>30?17:3)):0;ctx.fillStyle='#143c3940';ctx.beginPath();ctx.ellipse(p.x,p.y+4,22*s,6*s,0,0,7);ctx.fill();ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.face*(1+anim*.025),1-anim*.04);if(p.inv>0)ctx.globalAlpha=.55+Math.sin(time*35)*.25;if(atlas.complete&&atlas.naturalWidth){const cw=atlas.width/4,ch=atlas.height/2;ctx.drawImage(atlas,(p.id%4)*cw,Math.floor(p.id/4)*ch,cw,ch,-44*s,-78*s,88*s,88*s);}else{rounded(-20*s,-42*s,40*s,42*s,18*s,colors[p.id])}ctx.restore();if(p.power){ctx.strokeStyle='#d4fff3';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y-27*s,42*s,0,7);ctx.stroke()}ctx.textAlign='center';ctx.font='bold 11px Arial';ctx.fillStyle=p===pets[0]?'#e4ffaf':'#fff';ctx.fillText((p===pets[0]?'▼ YOU':names[p.id]),p.x,p.y-84*s);if(p===order[order.length-1]&&p.score>0){ctx.fillStyle='#ffe197';ctx.font='23px Arial';ctx.fillText('♛',p.x,p.y-99*s)}}
 for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.r,p.r)}ctx.globalAlpha=1;for(const r of rings){ctx.strokeStyle=`rgba(255,240,163,${r.life})`;ctx.lineWidth=5;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.stroke()}
 ctx.restore();}
function randSeed(i){return(Math.sin(i*317.8)*43758.5)%1*.5+.5}
function frame(t){const dt=Math.min((t-last)/1000,.033);last=t;update(dt);draw();requestAnimationFrame(frame)}
function togglePause(){if(!running||ended)return;paused=!paused;$('#paused').hidden=!paused;$('#pauseTitle').textContent='Taking a breather.';$('#pauseText').textContent='Your pets will wait for you.';$('#resume').textContent='Back to the chaos ➜';}
document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowLeft','ArrowRight','ArrowDown'].includes(e.code))e.preventDefault();if(!keys[e.code])pressed[e.code]=true;keys[e.code]=true;if(e.code==='Escape')togglePause()});document.addEventListener('keyup',e=>{keys[e.code]=false;if(['Space','ArrowUp','KeyW'].includes(e.code)&&pets[0]?.vy<-260)pets[0].vy=-260});window.addEventListener('blur',()=>{for(const k in keys)delete keys[k];if(running&&!paused&&!ended)togglePause()});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;pressed[b.dataset.key]=true});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{keys[b.dataset.key]=false})});
$('#choices').innerHTML=names.map((name,i)=>`<button aria-label="Choose ${name}" data-pet="${i}" class="${i===0?'selected':''}"><div class="pet" style="background-position:${i%4*100/3}% ${Math.floor(i/4)*100}%"></div>${name}</button>`).join('');$('#description').textContent=traits[0];$('#choices').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;selected=+b.dataset.pet;document.querySelectorAll('[data-pet]').forEach(x=>x.classList.toggle('selected',x===b));$('#description').textContent=traits[selected]});$('#play').onclick=start;$('#pause').onclick=togglePause;$('#resume').onclick=()=>ended?start():togglePause();$('#restart').onclick=()=>{running=false;paused=false;$('#paused').hidden=true;$('#menu').hidden=false};$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'♪̸':'♫';$('#sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound')};pets=names.map((_,i)=>pet(i,1000+i*230));makeMap();requestAnimationFrame(frame);
window.arenaDebug={start,update,makeMap,spill,get state(){return{pets,tokens,platforms,powers,time,mapIndex,particles,charge}},setTime(t){time=t;round=Math.floor(t/30);mapIndex=round%3;makeMap();},press(k){keys[k]=true;pressed[k]=true},release(k){keys[k]=false}};
